
env:
  global:
    - FLUTTER_VERSION=1.22.5
    - DOCKER_IMAGE=mobiledevops/flutter-sdk-image:1.22.5

matrix:
  include:
    - os: linux
      dist: bionic
      services: 
        - docker
    - os: osx
      osx_image: xcode12.3  

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker pull $DOCKER_IMAGE
      docker run --name android_ci -t -d $DOCKER_IMAGE /bin/sh
      
      tar Ccf . - . | docker exec -i android_ci tar Cxf /home/mobiledevops/app -
    fi
  
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      npm install -g fvm
      fvm stable > /dev/null
      fvm $FLUTTER_VERSION > /dev/null
    fi

script: 
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker exec android_ci flutter build apk
    fi
  
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      flutter build ios --release --no-codesign 
    fi
